### ISSUE TITLE
Custom Markes want show (still loads default)

### ISSUE THREAD

**Issue by marcorensch** [rvalitov/widgetkit-map-ex#18] opened 2016-02-14 18:42 UTC
on our page we're not able to setup custom markes as you describe in your Guide.
We use:
joomla 3.4.8 
widgetkit 2.5.3
Link: http://www.golferschoice.ch/karte

we've just settet up the general custom marker under Settings --> Map
The Widget is showing but not with our Marker, just with the default.
Also if we additionaly setup a custom icon for each element (after we have activated Custom in the settings) nothing changes. We have also tried to use different PNG Images (265x256px & 32x32px Size)
Please let me know if you need more details.
I dont see any error in the console - print debug info is turned on.

Our Settings and the Page screen:
![mapview](https://cloud.githubusercontent.com/assets/11912135/13035535/fdcca816-d352-11e5-8696-52b7a4f02f7d.jpg)
![generalsettings](https://cloud.githubusercontent.com/assets/11912135/13035537/01c33bb0-d353-11e5-998b-534edda72d21.jpg)

and one of the items:
![itemsetting](https://cloud.githubusercontent.com/assets/11912135/13036206/40dfa94c-d361-11e5-99d0-3894bb94f581.JPG)

kind regards
Marco

**Comment by rvalitov** [comment] 2016-02-14 22:01
Thank you for the detailed information. I have checked your website and the screenshots.
Unfortunately, I don't have good news for you. It seems that you did everything correctly and the configuration is fine. However, I don't understand why it doesn't work in your case. Actually, it's a very simple case, so that even the debug output doesn't generate anything here. Moreover, there are no errors in the console.

I don't have any ideas now. I have to see the back-end and try tweaking the settings of the widget and probably catch the error or find the reason of this problem. Please, send me the login/password to the back-end privately to this e-mail: ramilvalitov@gmail.com
Thank you!

**Comment by rvalitov** [comment] 2016-02-15 20:47
This issue is caused by conflict between the MapEx and the original Map widget. In some websites the Map widget loads first, thus it loads its own JS script for the Goolge Maps API and the script of the MapEx becomes second. But the Google Maps API allow only single (the first) script to load and use its API. That's why the script of the MapEx is being ignored causing all the advanced features (e.g. the custom icons) to be inactive. This issue is also connected with #5.

This issue will be fixed in the next release of the MapEx widget.

**Comment by rvalitov** [comment] 2016-02-20 23:50
- The issue is fixed in MapEx v1.4.3. 
- Some useful information regarding this issue is available in the Wiki ["MapEx and other plugins"](https://github.com/rvalitov/widgetkit-map-ex/wiki/MapEx-and-other-plugins).
- Now it's much easier to investigate the reason of a possible problem with widget owing to the new extended debug output, [read more](https://github.com/rvalitov/widgetkit-map-ex/wiki/Capturing-debug-output).

**Closed as completed by rvalitov** 2016-02-20 23:50 UTC
Labels: bug
