### ISSUE TITLE
The filed custom pin Image does not show up

### ISSUE THREAD

**Issue by fannynet** [rvalitov/widgetkit-map-ex#34] opened 2016-06-09 09:14 UTC
### Steps to reproduce the behavior

In Settings, select   the "Custom" option for the "Marker Pin Icon"
In content, add a new field : mange field + new field
### System information

**CMS type**:  WordPress

**CMS version**: WordPress 4.5.2 with  theme Nirvana.

**Version of the widget**:2.4.8

**Website URL**:yoga-en-provence.com

**Debug output of the widget**:

**Comment by fannynet** [comment] 2016-06-09 09:18
(I forget to say hello, then hello !)

**Comment by rvalitov** [comment] 2016-06-09 10:18
Hello,
thank you for reporting this! Yes, I'm aware of this situation, but I didn't write about it in the Wiki, because I thought it was very rare to happen. Now I made a dedicated [article](https://github.com/rvalitov/widgetkit-map-ex/wiki/Some-fields-are-missing) that describes this issue, please, follow the solution provided there. I would like to mention that this problem is not a bug of this widget. It happens, because some versions of the Widgetkit doesn't sometimes display correctly all the necessary fields (probably a bug of the Widgetkit). 

If the provided solution solves your problem, then please close this issue. Otherwise, write your comments below and I will try to help you with this problem and find another solution!

**Comment by fannynet** [comment] 2016-06-09 12:06
Hey! Thank you so much for your quick answer ! I ll try that and let you know ! Have a nice day !

**Comment by fannynet** [comment] 2016-06-09 12:34
Dear Ramil, 
I am trying the second solution (Manually) => Now, I do have the opportunity to load the new image (png), but:
-  it doesnt show up on the map, I still have the basic one. 
- I do not have the fields "Anchor" neither . 
  Any idea?

**Comment by rvalitov** [comment] 2016-06-09 12:54
You should add the 2 fields for both anchors, too, as it is written in the manual. After that if the problem will still exist, then please send me 2 screenshots of the widget:
- the _Content_ interface where I can see at least one item with location and pin image
- the _Map_ tab in the _Settings_ interface

**Comment by fannynet** [comment] 2016-06-09 13:43
Oh, I am sorry, I didnt read it very well then, I ll try that carrefully and let you know !

**Comment by rvalitov** [comment] 2016-06-17 23:54
Any news about this issue? Is your problem solved?

**Closed as completed** 2016-06-30 10:49 UTC
Labels: question
